/**
 * Full list of languages supported by Azure AI Translator.
 * BCP-47 codes as accepted by the /translate endpoint.
 */
export const AZURE_LANGUAGES = [
  { code: 'af',       label: 'Afrikaans' },
  { code: 'sq',       label: 'Albanian' },
  { code: 'am',       label: 'Amharic' },
  { code: 'ar',       label: 'Arabic' },
  { code: 'hy',       label: 'Armenian' },
  { code: 'as',       label: 'Assamese' },
  { code: 'az',       label: 'Azerbaijani' },
  { code: 'bn',       label: 'Bangla' },
  { code: 'ba',       label: 'Bashkir' },
  { code: 'eu',       label: 'Basque' },
  { code: 'bs',       label: 'Bosnian' },
  { code: 'bg',       label: 'Bulgarian' },
  { code: 'yue',      label: 'Cantonese (Traditional)' },
  { code: 'ca',       label: 'Catalan' },
  { code: 'zh-Hans',  label: 'Chinese Simplified' },
  { code: 'zh-Hant',  label: 'Chinese Traditional' },
  { code: 'hr',       label: 'Croatian' },
  { code: 'cs',       label: 'Czech' },
  { code: 'da',       label: 'Danish' },
  { code: 'prs',      label: 'Dari' },
  { code: 'nl',       label: 'Dutch' },
  { code: 'en',       label: 'English' },
  { code: 'et',       label: 'Estonian' },
  { code: 'fj',       label: 'Fijian' },
  { code: 'fil',      label: 'Filipino' },
  { code: 'fi',       label: 'Finnish' },
  { code: 'fr',       label: 'French' },
  { code: 'fr-ca',    label: 'French (Canada)' },
  { code: 'gl',       label: 'Galician' },
  { code: 'ka',       label: 'Georgian' },
  { code: 'de',       label: 'German' },
  { code: 'el',       label: 'Greek' },
  { code: 'gu',       label: 'Gujarati' },
  { code: 'ht',       label: 'Haitian Creole' },
  { code: 'he',       label: 'Hebrew' },
  { code: 'hi',       label: 'Hindi' },
  { code: 'hu',       label: 'Hungarian' },
  { code: 'is',       label: 'Icelandic' },
  { code: 'id',       label: 'Indonesian' },
  { code: 'ga',       label: 'Irish' },
  { code: 'it',       label: 'Italian' },
  { code: 'ja',       label: 'Japanese' },
  { code: 'kn',       label: 'Kannada' },
  { code: 'kk',       label: 'Kazakh' },
  { code: 'km',       label: 'Khmer' },
  { code: 'ko',       label: 'Korean' },
  { code: 'ku',       label: 'Kurdish (Central)' },
  { code: 'kmr',      label: 'Kurdish (Northern)' },
  { code: 'ky',       label: 'Kyrgyz' },
  { code: 'lo',       label: 'Lao' },
  { code: 'lv',       label: 'Latvian' },
  { code: 'lt',       label: 'Lithuanian' },
  { code: 'mk',       label: 'Macedonian' },
  { code: 'mg',       label: 'Malagasy' },
  { code: 'ms',       label: 'Malay' },
  { code: 'ml',       label: 'Malayalam' },
  { code: 'mt',       label: 'Maltese' },
  { code: 'mi',       label: 'Maori' },
  { code: 'mr',       label: 'Marathi' },
  { code: 'my',       label: 'Myanmar (Burmese)' },
  { code: 'ne',       label: 'Nepali' },
  { code: 'nb',       label: 'Norwegian' },
  { code: 'or',       label: 'Odia' },
  { code: 'ps',       label: 'Pashto' },
  { code: 'fa',       label: 'Persian' },
  { code: 'pl',       label: 'Polish' },
  { code: 'pt',       label: 'Portuguese (Brazil)' },
  { code: 'pt-pt',    label: 'Portuguese (Portugal)' },
  { code: 'pa',       label: 'Punjabi' },
  { code: 'ro',       label: 'Romanian' },
  { code: 'ru',       label: 'Russian' },
  { code: 'sm',       label: 'Samoan' },
  { code: 'sr-Cyrl',  label: 'Serbian (Cyrillic)' },
  { code: 'sr-Latn',  label: 'Serbian (Latin)' },
  { code: 'sk',       label: 'Slovak' },
  { code: 'sl',       label: 'Slovenian' },
  { code: 'so',       label: 'Somali' },
  { code: 'es',       label: 'Spanish' },
  { code: 'sw',       label: 'Swahili' },
  { code: 'sv',       label: 'Swedish' },
  { code: 'ty',       label: 'Tahitian' },
  { code: 'ta',       label: 'Tamil' },
  { code: 'tt',       label: 'Tatar' },
  { code: 'te',       label: 'Telugu' },
  { code: 'th',       label: 'Thai' },
  { code: 'bo',       label: 'Tibetan' },
  { code: 'ti',       label: 'Tigrinya' },
  { code: 'tr',       label: 'Turkish' },
  { code: 'tk',       label: 'Turkmen' },
  { code: 'uk',       label: 'Ukrainian' },
  { code: 'ur',       label: 'Urdu' },
  { code: 'ug',       label: 'Uyghur' },
  { code: 'uz',       label: 'Uzbek (Latin)' },
  { code: 'vi',       label: 'Vietnamese' },
  { code: 'cy',       label: 'Welsh' },
  { code: 'zu',       label: 'Zulu' },
];

export function getLangLabel(code) {
  return AZURE_LANGUAGES.find((l) => l.code === code)?.label ?? code;
}
